### ISSUE TITLE
QR code limitation with high-version symbols

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#314]
This image can be recognized with 53ded527ce0cfc88882b91a0a46fd189bc0d3d1b, but the current HEAD (1e39cbe0) fails to detect it.
![image022](https://user-images.githubusercontent.com/21275667/163757772-c99d31a2-dfd2-4cbf-b96e-584a8be10b58.jpg)

**Comment by axxel** [comment]
The line that caused this regression is the first changed in a92c351bd2efaadc6584f2adca8abd9c5600a1c3, which was a reversal of an earlier change that was flawed. I don't want to introduce that `centered()` call again because it is fundamentally no fix for the underlying limitation of the `EstimateModuleSize()` function. It is just pure luck that this slight shift in the start coordinate fixes this particular image. I'll try to find a more thorough improvement that generally deals better with these kind of large QRCode symbol situations.

**Comment by axxel** [comment]
For the future me or anyone who wants to work on this in the meantime: the way to handle this situation is to use the estimated module size to first sample the version info near the lower-left and upper-right finder patterns and get the real version of the symbol from there. See also how the MicroQRCode does this.
