### ISSUE TITLE
BitArray.h header no longer gets installed

### ISSUE THREAD

**Issue by berolinux** [zxing-cpp/zxing-cpp#361]
1.4.0 removes the BitArray.h header from PUBLIC_HEADERS. Since BitMatrix::getRow still returns a BitArray, I'm thinking this may be a bug rather than an intentional change.

BitArray is used among others by LibreOffice.

https://github.com/LibreOffice/core/blob/master/cui/source/dialogs/QrCodeGenDialog.cxx#L30
https://github.com/LibreOffice/core/blob/master/cui/source/dialogs/QrCodeGenDialog.cxx#L82

**Comment by axxel** [comment]
Sorry to hear this change is causing trouble. It was indeed a very deliberate decision, knowing the risk of missing some use case and potentially annoying someone. But I saw no practical way of figuring out beforehand who might be depending on what "internal" API. With knowingly public APIs I'm trying hard to provide a smooth transition (see 1.3 -> 1.4 -> 2.0).

Since this particular use case in LibreOffice does not make much sense from neither a performance nor readability perspective, I'd like to propose to change it there. Please have a look at [ToSVG](https://github.com/nu-book/zxing-cpp/blob/2dea5ec1373ed142efeedfc28f9eb1740fe352ed/core/src/BitMatrixIO.cpp#L37) and either copy that approach (`matrix.get(x, y)`) or maybe simply use `ZXing::ToSVG` as is (but that was only added in 1.4).

That said, I agree that it makes no sense to have that `Matrix::getRow` method and then not include `BitArray.h`. I should have removed/deprecated that method as well.

See also the second half of [this comment](https://github.com/nu-book/zxing-cpp/issues/335#issuecomment-1184461246) which was a reply to @a17r who probably ran into the same issue?

**Comment by axxel** [comment]
Are any of you (@berolinux or @a17r) in the position to provide a PR for libreoffice that does away with the use of `Matrix::getRow`? In 2.0 this method will be gone for good.

**Comment by axxel** [comment]
@cloph I saw [this comment](https://github.com/LibreOffice/core/pull/32#issuecomment-1122120968) of yours and wondered whether you would be willing feed a 3-line patch into the Gerrit machinery to remove the use of the deprecated `Matrix::getRow` call (see above).

**Comment by bwarden** [comment]
If it helps, here's the patch I created for Clear Linux:
https://github.com/clearlinux-pkgs/libreoffice/blob/main/0004-Remove-dependency-on-BitArray.h-from-zxing-1.2.0.patch

**Comment by axxel** [comment]
@bwarden thanks a lot for linking it here. If only someone found the time to feed this patch into the Gerrit issue/PR infrastructure they use. I don't have the time to do that.

**Comment by reneengelhard** [comment]
I could theoretically do this but this is no real help - actually @bwarden should do it anyway given it's his code and LO probably needs his license statement anyway (cf. https://wiki.documentfoundation.org/Development/gerrit/SubmitPatch#Add_yourself_to_the_contributor_list)

**Comment by axxel** [comment]
@reneengelhard please go ahead and submit something. If you don't want to infringe on @bwarden s copyright, just have a look at the above mentioned `ToSVG` code from zxing-cpp itself as a template to remove the `BitArray.h` dependency. For half a year now, I'm hoping someone with a working gerrit setup would be so kind to send in those 3 lines. This keeps coming up again and again.

**Comment by reneengelhard** [comment]
https://gerrit.libreoffice.org/c/core/+/144874

**Comment by axxel** [comment]
Awesome! Who could have thought that this would get all the way down into debian testing within just 2 days?!? :)

If anyone listing here has the means to test this easily, I'd be interested to know of the current HEAD (which will be 2.0 very shortly) works with libreoffice as is. If not, now I still have the time to fix any upcoming issues.

**Comment by reneengelhard** [comment]
> If anyone listing here has the means to test this easily, I'd be interested to know of the current HEAD (which will be 2.0 very shortly) works with libreoffice as is. If not, now I still have the time to fix any upcoming issues.

seems so, at least buillds and links after nudiging LO in finding it in /usr/local after removing Debians packages
