### ISSUE TITLE
BitSource::readBits: out of range Issue

### ISSUE THREAD

**Issue by FGAamaris** [zxing-cpp/zxing-cpp#392]
Hi everyone,
I am using this library for a project and I encountered this exceptions "BitSource::readBits: out of range". 
I only read DataMatrix 10x10 and sometimes the DM are dirty.
It's quite difficult for me to provide images where I can replicate the exception because it's a fast application (35Hz for 480x300 images) and the problem doesn't happen quite often ( twice in a weekend).
This exception seems to be generated while decoding the bits retrieved from the DMDetector. The only moment where there is not a control before the BitSource::readBits Method seems to be in the DecodeBase256Segment.
I think that my Issue is that the dirt on the DM lead to a fake Mode::BASE256_ENCODE and then the readbits read more bits then the available, but this is just my point of view.
Is there any way to prevent this exception.
Thank you very much for your attention
Filippo

**Comment by axxel** [comment]
I don't know what the cause of your problem is but I have two data points that let me question your analysis:
 1) there is a fuzzer for the DMDecoder available and I just re-ran it without any issue showing up
 2) the bits that are decoded are already error-corrected which make it extremely unlikely that noise/dirt on your image may result in a stream of checksum corrected bits with faulty bits in them. Meaning, if the bitstream would be corrupt in a way as you describe, it would already need to be encoded like this and noise would have nothing to do with it.

I think the best chance of finding the cause of the issue is for you to modify your setup such that it dumps the image input in case it detects this exception and then post this image for me to have a look at.

**Comment by FGAamaris** [comment]
Thank you @axxel for your suggestions.
I will try to retrieve those information.

**Comment by axxel** [comment]
Any luck with reproducing the problem?

**Comment by FGAamaris** [comment]
I've set a try catch statement and then I tried to re-run the image "catched" but it didn't repeat the error.
At this point I tought that it would be meaningless to share it.
Thanks for the support
Filippo

**Comment by axxel** [comment]
That means your issue is not reproducible anymore? In that case, please close the ticket.
