### ISSUE TITLE
Image triggers assertion

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#399]
This image triggers assertion on https://github.com/zxing-cpp/zxing-cpp/blob/master/core/src/Result.cpp#L127
Apparently this assertion is a no-op in release build but it blocks me from debugging `zxing-cpp` in debug builds.

**Comment by duanqn** [comment]
Well, I think it's best not to pose the image publicly, but I do want to understand the implication of this `assert`. It seems the result is OK even though the assertion is triggered in debug mode.

**Comment by axxel** [comment]
This assertion is explained by the comment directly above it. It firing indicates a bug in the code to me if the `operator==` is called from within the library. I implemented only this case because it is the only case that was relevant at the time.

Maybe sending the image to me personally would be acceptable, then I can have a look.

**Comment by duanqn** [comment]
OK I will handle this next week. Maybe it still repros after masking some personal information on the image.

**Comment by duanqn** [comment]
![edited](https://user-images.githubusercontent.com/21275667/189060574-adc7574a-1301-4f39-b15a-6b39b010afce.jpg)


This image triggers assertion on commit 047143277e7810600292bc8a52ddb203248c7e8f (latest)
