### ISSUE TITLE
Crash happens with the given image

### ISSUE THREAD

**Issue by liuyl07** [zxing-cpp/zxing-cpp#413]
I am very interested but also new to the library, so I familiarize myself by playing with ZXingReader.exe with various test cases (forgive me if they test cases are foolish and you can ignore this issue). 

I compiled the master branch with the commit 698a7c53

However, it is found that the program crashes the system with the below image having 3 codes
![8_datamatrix](https://user-images.githubusercontent.com/15646535/190994384-a222e75d-dd08-4215-b8b4-742770d06657.png)
![image](https://user-images.githubusercontent.com/15646535/190994452-2a757f55-acc7-46c7-b8cf-25f184c7abea.png)

**Comment by axxel** [comment]
The problem is the MicroQRCode (the lower) symbol. It is pretty much an exact duplication of #404. There is some proper content (in this case 'dynamsoft') and then 2 '0'-bits left in the second last byte, followed by the last byte `0b1100'0000`. MQR Version 3 symbols need 7 0-bits terminator. Reading 7 bits results in `0b0011000 != 0`, so it reads 2 mode bits (both 0 -> numeric mode), then 5 count-bits (`0b11000 == 24`) and then tries to read those 24 characters, which means a total of 80 bits while only 3 bits are left.

According to my understanding of the spec this is an invalid symbol. Where did you get this from?

@gitlost can you confirm my interpretation of the specification?

**Comment by liuyl07** [comment]
@axxel Thank you for your kind reply.

The symbol was from Google Image as below
![image](https://user-images.githubusercontent.com/15646535/191052877-ed5747b6-e989-4ac5-8b92-a9102de0cfae.png)

**Comment by gitlost** [comment]
Hi yes my interpretation confirms yours and the last nibble (as M3's finish with 4-bits) should be `0b0000` instead of `0b1100` (guessing that whatever produced this used the bottom nibble of the pad byte `0xEC` instead of truncating the terminator to 6-bits).

So as indicated in #404 the exception should be trapped and a `FormatError()` returned as done for Aztec Code (https://github.com/zxing-cpp/zxing-cpp/blob/master/core/src/aztec/AZDecoder.cpp#L308), so such errors can be ignored or dealt with by the application as it wishes.

("PDFScanningDecoder.cpp" should also trap such exceptions.)

(I note that Dynamsoft's own reader https://demo.dynamsoft.com/barcode-reader/ returns the barcode, without it appears indicating any format error.)

**Comment by axxel** [comment]
Note: with the recent commit this symbol is now invalid / erroneous hence the result has the error flag set and is only reported if
`DecodeHints::returnErrors` is set. See `-error` option of `ZXingReader`.
