### ISSUE TITLE
Make this the "official" zxing-cpp?

### ISSUE THREAD

**Issue by simonschmeisser** [zxing-cpp/zxing-cpp#44]
There are currently hundreds of forks of zxing-cpp out there with two main "base"-forks as far as I can tell: this one and https://github.com/glassechidna/zxing-cpp

For concentrating efforts and for packaging in distributions (linux, chocolately, home-brew, ports, ...) it would be great to have one "main" fork. This one seems to be a) the most active in recent times, b) has unit tests for all codes and c) has a version number/release since yesterday. So if you agree it would be great to focus on this one.

Any thoughts or objections?

We could even "move" it to zxing/zxing-cpp or zxing-cpp/zxing I guess

**Comment by simonschmeisser** [comment]
there was a question about API compatibility at https://github.com/glassechidna/zxing-cpp/issues/68#issuecomment-443129574 would you like to comment?

**Comment by axxel** [comment]
I would certainly welcome making this fork the "official" one. Drawing some attention was my secret plan when I commented on a couple of issue tickets in the 'other' fork ;). Probably unique to this fork (as I perceived it, when I was looking for a c++ version of xing originally) is that it is not based in any way on the original zxing-cpp code base but is a complete rewrite based on the then most recent Java version with a 'native c++-11' flavor in mind (instead of trying to mimic the JAVA api 1:1. I.e. e.g. no `Ref` class in the API).

Even though I contributed a bit of c++ 'cleanup' type of changes, a few minor detection improvements for 1D bar codes and reimplemented the DataMatrix detector, this fork is really @huycn work. So it is definitively his call regarding how this fork should move forward (or not).

I expect there might be some more 'plumbing' necessary if the code base is exposed to more OSes / compiler versions but nothing I'd worry about.

**Comment by huycn** [comment]
Me too, I have no objection and will be happy make this the "main" c++ fork. I'm certain that my boss, @ChantalLemay, would agree with me on that. I wonder what is the most efficient way to make this happen. I will probably contact maintainers of original ZXing repo.

**Comment by simonschmeisser** [comment]
Great news! Contacting the ZXing maintainers sounds like a very good way forward. It would probably also simplify distributing maintenance effort across more shoulders (if desired). Thanks!

**Comment by huycn** [comment]
Thank to Sean Owen, we have now a link from ZXing project page to this repo.

**Comment by axxel** [comment]
As I see it, the glassechidna port is now effectively abandoned (last commit was 3 years ago). I don't expect any reaction to my "Join forces" issue anymore. So I guess this port is now as "official" as it will get. I would actually go as far as to argue that this is now **the** official zxing project. ;). Anyway, I hereby close this issue.
