### ISSUE TITLE
Barcodes that cannot be recognized

### ISSUE THREAD

**Issue by duanqn** [zxing-cpp/zxing-cpp#454]
Hi, I need some help with this image:
![1](https://user-images.githubusercontent.com/21275667/205806999-933e839b-b61a-4417-bde6-4e188ea9b196.png)

Although the image is a bit blurry, I think it should still be feasible to recognize. However I tested with the latest version and ZXingReader failed to recognize it. Is there any other configuration I can try?

**Comment by duanqn** [comment]
I have another image here:
![0](https://user-images.githubusercontent.com/21275667/205826410-9e232fa9-7a0d-4cb4-9453-7f4ab0cf291a.png)
It looks really clear but cannot be recognized.

**Comment by axxel** [comment]
ad QR sample: As you can see in the following debugging output image, the sample grid placement was as good as it gets.
![#454-grid](https://user-images.githubusercontent.com/1038346/205881217-376f6752-f708-43be-96d7-437187fe8849.png)

The symbol fails to be detected because of a checksum error. If the resolution would be just a little higher, I believe it would work. There is something a little off with the horizontal 'center line'. Maybe an aliasing artifact.

ad PDF417 sample: Similar situation, meaning a failed detection because of a checksum error. Here is seems to be obviously an aliasing issue. E.g. the the 3 narrow lines next to the wide one on the left are supposed to be equally wide but the last of them is twice as wide as the other 2. This happens when someone scales a 100px wide image to say 110px with a nearest neighbour scaling, in that case it would simply add 10 columns as a copy of the one next to them, which completely distorts the relative widths.

**Comment by axxel** [comment]
I might have used the term "aliasing" a little loose here or maybe even simply wrong. There is a very good article from @terryburton that describes the issue (I can't find it right now, so maybe I got this mixed up somehow). The problem is that this PDF417 code is generated or scaled wrong and therefore broken. If you have a symbol that is rendered with a module size of 1 pixel then you can not simply make it 10% bigger with this kind of nearest neighbor resampling because some bars/spaces that were 1 module wide will now be 2 modules wide (instead of all of them 10% wider). If the module size is 10 pixels, say, this will work just fine because a 10 pixel wide bar will become 11 pixel wide, which is 10% wider than 10 pixels not 100% wider as with the 2 vs. 1 pixels.

I don't see a simple preprocessing technique to fix this particular symbol.

**Comment by terryburton** [comment]
Perhaps this: https://stackoverflow.com/a/36204327/2568535

"Aliasing" is well understood as referring to statistical aberrations in the binarized image, as opposed to systematic effects such as print growth seen in the original image.

The Reference Decode Algorithms for matrix symbologies typically refer to evaluating ~25% of the centre pixels of each detected module which helps to compensate for print growth/loss, poor focus, jagged/unstable edges due to lack of grid-fitting, etc. but this doesn't help so much with effects arising from uneven lighting and excessive scan angles.

For mobile cameras, you get a similar effect to Gaussian blur due to progressive auto-focusing. In my limited experience with decoding, this generally doesn't help provided that the black/white threshold finding is already done well.

**Comment by duanqn** [comment]
Many thanks to both of you sharing your expert knowledge! 👍 
Also, @axxel you may be interested to know that I found a solution for the QR code image. There is a super resolution model available at https://github.com/opencv/opencv_3rdparty/tree/wechat_qrcode_20210119. I ran it with the given image and the result is this:
![out](https://user-images.githubusercontent.com/21275667/206148441-02164149-e307-4b8b-9a81-dd6426b90e20.png)

This image can be recognized by ZXing-cpp. I can definitely work on integrating that super resolution model into zxing-cpp if you think it's a good idea.

**Comment by axxel** [comment]
Thanks for your offer to look into contributing the mentioned NN-model for up-sampling images. I believe that in terms of performance, it is a bad idea to incorporate a general upscaling of the input. But I'm sure there is something to gain during the sampling by incorporating a NN. I believe the following approach would be good:

1) perform the sampling just as it is done right now and if we run into a checksum error:
2) for each subpixel position of the sampling grid, go back to the original grey-scale input and use a NN to determine if that position is either white or black.

Maybe there is a model to be found that can do that, or just needs a little modification.

**Comment by axxel** [comment]
I just stumbled upon the information that I had in the back of my mind when I was talking about "aliasing". It is not quite the issue above but related. @terryburton writes about "pixel grazing" here: http://slides.com/terryburton/barcode-writer-in-pure-postscript#/12
