### ISSUE TITLE
QR not recognized

### ISSUE THREAD

**Issue by mbaros100** [zxing-cpp/zxing-cpp#485]
What is the reason this QR is not being recognized?

https://products.aspose.app/barcode/recognize

can recognize

**Comment by axxel** [comment]
This symbol is broken because the overlay in the center is larger than what the used error correction level can compensate for. The authors of this symbol basically did not know what they were doing. It is exactly the same problem as the one discussed [here](https://github.com/zxing/zxing/issues/1530#issuecomment-1133634619).
