### ISSUE TITLE
Uncaught exception when decoding particular MicroQR

### ISSUE THREAD

**Issue by pictview** [zxing-cpp/zxing-cpp#490]
When decoding a particular MicroQR, CodecModeForBits() throws std::invalid_argument which is then not caught by QRCode::DecodeBitStream(). An android app decodes "barcode xpress" in there, but I can't claim the barcode is 100% valid as other readers fail as well.
Is it expected that MultiFormatReader::read() throws?
Please note also the typo in the name of the 2nd argument of CodecModeForBits() - isMirco
![image](https://user-images.githubusercontent.com/87663700/212737156-6f581480-6cfc-4191-8eee-31d1ba46d62a.png)

**Comment by duanqn** [comment]
Not directly solving your problem, but I generated a MicroQR code encoding "barcode xpress" with Zint:
![generated](https://user-images.githubusercontent.com/21275667/212801835-5d92b2d9-886c-4755-b441-8cdfd377b59c.png)

**Comment by axxel** [comment]
> Is it expected that MultiFormatReader::read() throws?

Not in this case. See fix.

The symbol itself is violating the specification, though. (As far as I can tell).

**Comment by pictview** [comment]
Thanks for the fix, it is certainly correct. However, I am still wondering why other reader(s) can read the barcode. So I did some digging. 
The capacity of 17x17 L microQR is 16 bytes. The encoded string occupies exactly 15 bytes. Then the Terminator should follow - nine 0 bits. The QR ISO 18004-2006 specification says _“The end of the data in the complete symbol is indicated by a Terminator consisting of between 3 and 9 zero bits (see Table 2), which is omitted or abbreviated if the remaining symbol capacity after the data bit stream is less than 4 bits.”_. So, we have 8 bits remaining, but the generator did not fill them with zeros, but put 0xEC there. Which seems to be half of the padding double-word: 0xEC11. So, the generator followed the “_omitted_” part and not  the “_abbreviated_” part because strictly speaking there are more than 4 bits remaining. So, literally, the barcode follows the specification. Logically, it does not, because the specification IMHO is wrong, it should consider the fact the Terminator is 3, 5, 7, 9 bits long for MicroQR and 4 for QR. So, what can fit into the 8 bits other than incomplete Terminator? Actually nothing. Mode has 3 bits, followed by a counter having at least 3 bits and then not even a single character can fit. Therefore I suggest to change the condition "bitsAvailable == 0" in IsEndOfStream() to "bitsAvailable < bitsRequired".

**Comment by axxel** [comment]
I appreciate your analysis and your attention to detail. I could not make any sense of your citation _"if the remaining symbol capacity after the data bit stream is less than 4 bits"_. So I double checked in the spec. I only have the more recent ISO 18004-2015 and there it reads in 7.4.9: _"The Terminator shall be omitted if the data bit stream completely fills the capacity of the symbol, or abbreviated if the remaining capacity of the symbol is less than the required bit length of Terminator."_ I hope you can agree that this makes perfectly clear that your symbol is violating the specification, since those remaining 8 bits _have to be_ `0`. If you can, do you also concur that the code as is correctly implements the specification?

As to your suggested code modification: I can follow your thought for this particular situation (M4, bits.available() == 8). But I did not go through all the other possible circumstances where `bitsAvailable < bitsRequired` to convince myself that this change does not break other (potentially valid) symbols. While that may be, my 'default' stance on the matter is that people with buggy encoders should fix their code instead of make all the decoders work around those bugs.

Do you have any idea where this image came from? Can you get in touch with the people responsible for it?

**Comment by pictview** [comment]
Your citation from the new spec shows that they fixed the wording. So, yes, I do agree the barcode violates the 18004-2015 spec. The barcode content helped to find the likely creator and I found the barcode at https://help.accusoft.com/BarcodeXpress/v13.5/BxNet/micro_qr.html. I have contacted them.

I think it is a not easy decision for you: do you want to strictly follow the specifications or go beyond? Some other vendors call their ability to decode barcodes others can't decode a competitive advantage. In my opinion, the latter is better, whenever there is no ambiguity, like in this case.

**Comment by axxel** [comment]
Thanks for helping, making the world a better (barcode) place :).

> whenever there is no ambiguity, like in this case.

As explained above, I am personally not convinced yet about the absence of ambiguity in all possible cases.

**Comment by axxel** [comment]
> I have contacted them.

@pictview I'm curious: did you get any reaction from them?

**Comment by pictview** [comment]
> > I have contacted them.
> 
> @pictview I'm curious: did you get any reaction from them?

Not at all :-(

**Comment by axxel** [comment]
Ah, commercial vendors.... they have their priorities straight ;).

If you still care about this particular issue, please feel free to help me get convinced about the "absence of ambiguity in all possible cases" so we might change the code such that your 'broken' image works.
