### ISSUE TITLE
EAN-13 cannot be recognized [quiet zone]

### ISSUE THREAD

**Issue by zuopengchi** [zxing-cpp/zxing-cpp#526]
Hi, 
We are using the ZXingCPP WebAssembly (version 1.4.0) to scan barcode. 
When we want to scan one product barcode, it’s failed. 
![om](https://user-images.githubusercontent.com/111266960/223298821-f7ccd8b9-8ac3-427a-9891-6dc3d444a8f1.jpg)
But this barcode can be scanned successfully by others library(e.g. ZXing-js https://zxing-js.github.io/library/examples/multi-camera/). By analyzing the barcode, we found that there is the border-right of brand label beside the End marker of Barcode. If the border-right of brand label is covered, the barcode can be scanned successfully by ZXing-cpp. 
It should be one issue about decoding the End marker of Barcode.

**Comment by axxel** [comment]
The problem is that the quiet zone on the right is insufficient. That means this symbol is not a valid EAN-13 symbol according to the specification, which requires a 7 module wide quiet zone on the right. The code currently enforces at least 6 (see [here](https://github.com/zxing-cpp/zxing-cpp/blob/d917ffb64685dfc8d3da146a48760f1646cd48a0/core/src/oned/ODMultiUPCEANReader.cpp#L37)). If you set the value to 3, it detects your sample successfully. This does increase the likelihood of detecting a false-positive code though and slightly increases the runtime.
