### ISSUE TITLE
Cannot read EAN13 code but zxing.net can [quiet zone]

### ISSUE THREAD

**Issue by isatalhamengi** [zxing-cpp/zxing-cpp#558]
Hi, 

I am using zxing algorithm for 1D or 2D barcodes and I have a problem which I cannot fix. I cannot read the barcode in the attached picture. I didn't understand why. Other zxing algorithms can read this barcode like Zxing.NET or Zxing Online Decoder but zxing-cpp cannot read. Could you please help me? I am stuck. Thank you.
![test_19](https://user-images.githubusercontent.com/102647476/236615693-349bc9d8-6ed7-4b3b-a337-d126b5b0d42c.jpg)

**Comment by axxel** [comment]
The problem here is lighting: the relatively dark pixels left and right of the barcode itself are sometimes interpreted as 'black' thereby breaking the quiet zone that is mandated by the specification. If you have control over your capture process, try to make it a little bit brighter.

You can make this particular image work if you do either of the following:
 * `hints.setDownscaleFactor(2); hints.setTryDownscale(true);`
 * `hints.setBinarizer(Binarizer::FixedThreshold);`

**Comment by axxel** [comment]
This is related to #526 and #509. Lowering the quiet zone requirement from 6 modules to 4 modules would also fix this particular image. But if the next one would be just a little darker than it would break again.

**Comment by isatalhamengi** [comment]
First of all, thank you so much. Another example is here. I set all hints but I cannot read again.  What is problem?
![test_4](https://user-images.githubusercontent.com/102647476/236620460-26b67ecf-919f-4aac-bf31-273bff2fe293.jpg)
