### ISSUE TITLE
Some pictures make infinite code loops.

### ISSUE THREAD

**Issue by Fogrunner** [zxing-cpp/zxing-cpp#570]
Hello. 

I am using c++ ZXing library. First of all, thanks for sharing nice library.

During using the library i have faced a big problem.

Some of images file from my client makes infinite loops 

In DMDetector.cpp

```
bool traceGaps(PointF dEdge, RegressionLine& line, int maxStepSize, const RegressionLine& finishLine = {})
{
line.setDirectionInward(dEdge);
int gaps = 0;
do {
...
  if (stepResult != StepResult::FOUND)
     // we are successful iff we found an open end across a valid finishLine
     return stepResult == StepResult::OPEN_END && finishLine.isValid() &&
     static_cast<int>(finishLine.signedDistance(p)) <= maxStepSize + 1;
   } while (true);
}
```

If i use the problem picture to read qrcode, the application cannot leave the above dowhile code. Not all images are like that. Some of images makes the problem. Both the pictures with and without the problem were taken with the same camera.

(Unfortunately, the photo has the problem contains customer information, so it is regrettable that we cannot share it.)

The above case occurs when using  'ZXing::Binarizer::LocalAverage', but does not occur when changing to the 'ZXing::Binarizer::GlobalHistogram'.

My client demand to use ZXing::Binarizer::LocalAverage, becuase the result is better than.

Please,  give me piece of advices.

**Comment by axxel** [comment]
I have two suggestions:

1. if you do not care about DataMatrix symbols then use the `DecodeHints::setFormat()` function to exclude DataMatrix. This will immediately solve your problem.
2. if you do care or you simply want to help with improving the library, please try your problematic images and remove the customer information. There is a good chance that the endless loop is still triggered if it was caused by something from the background and not the QRCode itself.

**Comment by axxel** [comment]
> My application has to determine QR Code is exists inside picture or not. So, i need to check DataMatrix formats.

I don't understand that statement. If you only interested in QRCode, then use `hits.setFormats(BarcodeFormat::QRCode);` this will solve your problem with the DataMatrix detector bug and be _a lot_ faster than what you have now, as well.

> I'm really confused what the problem is.

The problem is a bug in the algorithm I wrote.

> Could you please check the test file above?

Yes. Thanks for the image. I'll find a fix and publish it soonish.

**Comment by Fogrunner** [comment]
Thank you, @axxel 

I misunderstood that the values ​​included in MatrixCodes should not be set.
After setting setFormats(BarcodeFormat::QRCode), It seems working well.

Thank you so much for the very quick response and support.
