### ISSUE TITLE
Issues with inverted / dotted DataMatrix

### ISSUE THREAD

**Issue by lzp0916** [zxing-cpp/zxing-cpp#575]
![1234](https://github.com/zxing-cpp/zxing-cpp/assets/46048303/20af0d23-de59-439a-8a61-8e95f68bce22)
![1236](https://github.com/zxing-cpp/zxing-cpp/assets/46048303/24f5ea0f-b545-46f8-8024-564a74e91283)
![1235](https://github.com/zxing-cpp/zxing-cpp/assets/46048303/e8137e81-3353-4f75-bfc9-dd73780fba65)

**Comment by axxel** [comment]
This is related to #53 but due to the low resolution and slightly blurred image, the dotted part is actually not the main problem here. It is also related to #189.

So if you compile your zxing-cpp library with c++20 enabled you should be able to decode the second sample with `ZXingReader` as is (note the default for the `tryInverted` property is true).

The first sample still fails because the inversion happens after the binarization (for performance reasons) and the `LocalAverage` binarizer has a bias for light backgrounds. If you invert the image outside of zxing-cpp, then the first sample also works. If you generally have to deal with inverted DataMatrix input like all those 3 samples, I would recommend to invert the images and then set `DecodeHints::tryInverted(false)`.

The last samples still fails and that is because the resolution of the symbol is a little bit too low.

**Comment by axxel** [comment]
If you don't have anything more to add to this discussion, please close the issue.
