### ISSUE TITLE
reading rotated `pure` QRCode and DataMatrix barcodes

### ISSUE THREAD

**Issue by a3emdot** [zxing-cpp/zxing-cpp#589]
Hi there,

I wonder what one has to do for configuring zxing-cpp properly
such that it is possible to read 90, 180 and 270 degree rotated barcodes.
The barcodes in question are created unrotated with the help of zint
and are then rotated for testing purposes.

Here is a link to my github project with the relevant commit.
[zintzxingcppdemo](https://github.com/a3emdot/zintzxingcppdemo/commit/d1684b625c409e0e52e6b990420c5dc78f8ca5bd)

For building the project I used a Fedora installation with a properly setup developer installation.
It should be possible to run the reproducer simply by calling the bash script from the repo

cd zintzxingcppdemo
./ZintZXingCppDemo.sh

Observation: One can see a lot broken Tests in LastTest.log, either DataMatrix barcodes or QRCode barcodes.
Goal: A "clean" LastTest.log

Question: Is it intended that 'hints.setTryRotate(true)' and  'hints.setIsPure(true);' work together properly?
(all other tested symbologies don't have this issue, the can be read even without 'hints.setTryRotate(true)' )

- Andre

**Comment by a3emdot** [comment]
[LastTest.log](https://github.com/zxing-cpp/zxing-cpp/files/12052232/LastTest.log)

**Comment by a3emdot** [comment]
I currently use the revisions zint (fae3e6d9) and  zxing-cpp (6f4affc5)

**Comment by axxel** [comment]
> Question: Is it intended that 'hints.setTryRotate(true)' and 'hints.setIsPure(true);' work together properly?

No, it is not. The (or maybe 'my') definition of "pure" is a symbol that has no rotation, no skew, no noise, no nothing. `hints.setTryRotate(true)` has no effect anyway, since the default is `true`. Other barcodes might work because they don't have a special `isPure` implementation, so they perform the normal detection (including the rotation check). That is not true for PDF417 which actually has an `isPure` implementation that honors the rotation flag. That is mostly because there is actually an incentive to print rotated PDF417 symbols because of the non-square form. That is admittedly also true for rectangular DataMatrix symbols and could potentially be seen as bug.

`isPure` is only meant to make the detection faster (if implemented). Neither setting `isPure` nor `tryRotate` should fix your issues. If you really care about performance, then use the `DecodeHints.setFormat()` method to search only for the symbology you are interested in.

**Comment by axxel** [comment]
If there is nothing more, you'd like to add to this discussion, please close this issue.

**Comment by a3emdot** [comment]
I still find it somehow annoying that all my other used barcode types don't have this issue.
Could you perhaps tell what the background is for this?

**Comment by axxel** [comment]
I guess live can be inconvenient at times ;). The reason this does not work is, because it is not implemented. See my comment above.

I'm still wondering what your use case is. See my unanswered question to you on #590.
