### ISSUE TITLE
Fail to scan well-cropped image but Can scan raw image

### ISSUE THREAD

**Issue by Felix00643298** [zxing-cpp/zxing-cpp#595]
Hello, 
today I encountered a strange situation while using the latest zxingreader. I have an image that contains both a barcode and a QR code. These codes are positioned far away from the camera, upside down, and at various angles. Surprisingly, zxingreader successfully recognizes them in their original state. However, when I preprocess the image by rotating and cropping it to an optimal position, zxingreader fails to recognize the barcode anymore. It's puzzling because I haven't made any other changes to the image. Can anyone provide any insights into this issue?
Thanks in advance.

**Comment by axxel** [comment]
I need the image that fails to be able to say anything.

**Comment by Felix00643298** [comment]
> I need the image that fails to be able to say anything.
Can i send it to u vis email? Somehow can't upload raw image.

**Comment by axxel** [comment]
yes. You can use zxingcpp (at) gmail.com

**Comment by Felix00643298** [comment]
> yes. You can use zxingcpp (at) gmail.com

I have sent it to you.

**Comment by axxel** [comment]
The DataMatrix code (there is no QRCode in this image) fails to be detected in your cropped version because it is not in the center anymore. You need to compile the project with C++20 enabled. See #189 and the `Note` section in the [README](https://github.com/zxing-cpp/zxing-cpp#supported-formats).

The Code128 probably fails because it was barely detectable in the first place and the resampling changed a few relative grey scale values and now it fails. I assume the problem is caused by the narrow white lines that are pretty dark due to the lack of sharpness.

**Comment by Felixlovescode** [comment]
> The DataMatrix code (there is no QRCode in this image) fails to be detected in your cropped version because it is not in the center anymore. You need to compile the project with C++20 enabled. See #189 and the `Note` section in the [README](https://github.com/zxing-cpp/zxing-cpp#supported-formats).
> 
> The Code128 probably fails because it was barely detectable in the first place and the resampling changed a few relative grey scale values and now it fails. I assume the problem is caused by the narrow white lines that are pretty dark due to the lack of sharpness.

Hey, I am not an expert in computer vision. Can you simply explain why crop images can change grey scale values? Thanks.

**Comment by axxel** [comment]
> Hey, I am not an expert in computer vision. Can you simply explain why crop images can change grey scale values? Thanks.

It is not the cropping, it is the rotation (of anything other than a multiple of 90°) that requires a resampling of the image.

**Comment by Felixlovescode** [comment]
> 

I still have some doubts:

1. I have tried cropping the image without rotation, such as keeping only the right half or removing irrelevant areas at the top and bottom. However, it still fails to recognize code128. What could be causing this issue?

2. Should I apply rotation preprocessing on barcodes with rotation angles? I noticed that zxing offers this functionality, but I'm unsure if it is necessary or beneficial.

3. Would you recommend performing operations like enhancing contrast during the image preprocessing stage?

**Comment by axxel** [comment]
>     1. I have tried cropping the image without rotation, such as keeping only the right half or removing irrelevant areas at the top and bottom. However, it still fails to recognize Code128. What could be causing this issue?

It could indeed be that a simple crop has an influence on the outcome and that is because the library does not scan each and every row, especially in high resolution images. And if you have a situation where the code can only be detected on say a single row it could be that cropping causes this row to end up not being scanned. Can you post the cropped image that fails?

>     2. Should I apply rotation preprocessing on barcodes with rotation angles? I noticed that Zxing offers this functionality, so I'm unsure if it is necessary or beneficial if I do so.

The `tryRotated` flag does only add 90° rotation checks. If your linear barcodes are rotated such that you can't draw a single horizontal or vertical line over the code such that this line crosses the complete barcode, then zxing-cpp can't detect this barcode at all. In that case rotating it by whatever means can only improve the situation. You can consider a pre-processing rotation to be generally an improvement except for situations where the resolution of the image is close to the limit for the detection to work at all.

>     3. Would you recommend performing operations like enhancing contrast during the image preprocessing stage?

In general, yes. I recommend to make experiments with your particular input and use what works best.

**Comment by Felix00643298** [comment]
Thanks for replying me.
