### ISSUE TITLE
Zxing-cpp python can read code128 in jpg format but not in png format.

### ISSUE THREAD

**Issue by Felix00643298** [zxing-cpp/zxing-cpp#598]
Hello，
today, I encountered a problem related to zxing-cpp python 2.1.0 version. Specifically, when using zxingcpp.read_barcodes to read a png image, it failed to recognize the barcode on the image. However, when I saved the same image in jpg format using OpenCV and then tried reading it again with zxingcpp.read_barcodes, it successfully recognized the barcode. It is worth noting that png images generally retain more details compared to jpg images. The reason behind this difference is still unclear to me.

Thanks in advance,
Felix

**Comment by Felix00643298** [comment]
By the way, using the current demo reader, barcode can be successfully recognized regardless of whether it is in jpg or png format.

**Comment by axxel** [comment]
Your claim that `zxingcpp.read_barcodes` works with jpg but not with png files, does make any sens to me, because this function does not operate on files, it operates on python array buffers, like numpy ndarray objects.

If you have a png file that does "not work" and you have a jpg file containing "the same" image that works, then please post both images here and I can look into it.
