### ISSUE TITLE
QR Code Model 1 not supported

### ISSUE THREAD

**Issue by sayzzy-nt** [zxing-cpp/zxing-cpp#614]
First of all, thank you for providing such a nice library.
This QR code is not recognized, but I don't know what the problem is.

The smartphone app recognized it, so I don't think the QR code is broken.

![errorQR1](https://github.com/zxing-cpp/zxing-cpp/assets/136289338/91f2cb7f-0bdd-4722-8f5c-1b69e9becace)

**Comment by axxel** [comment]
I do believe that this symbol is in fact invalid. It is correctly detected but could not be decoded due to a checksum error. I checked the sample grid if there was an issue there but the grid placement is perfectly fine. I also tried to decode this image with a couple different online scanners and all agree that there is no valid qrcode to be found.

Which "smartphone app" were you using and what was the content of the detected qrcode?

**Comment by sayzzy-nt** [comment]
The app I was using was "QRQR"
And the string read is "766400488514071012112935"

I have attached the app URL below.
https://www.denso-wave.com/en/system/qr/product/reader.html

**Comment by axxel** [comment]
Thanks for the information. I found out what the issue is: the image you provided contains an (old/outdated) QR Code Model 1 (as opposed to the Model 2). According to the ISO specification, "Model 1 of QR Code, as defined in AIM ITS 97-001, is the form of the symbology originally used for a number of early or closed systems applications but is not recommended for use in new or open systems applications [...]". Model 1 codes are simply not implemented. If you need support for those and have some money to throw at the problem, please get in touch with me via zxingcpp (at) gmail.com.

**Comment by sayzzy-nt** [comment]
thank you for your reply.

I'm sorry if my understanding is wrong.
I believe that the difference between Model 1 and Model 2 of QR codes is the presence or absence of alignment patterns.
However, this library may be able to read her QR code without alignment pattern.
I don't know what the difference is.
I hope you'll tell me.

I have pasted the QR code read by "zxing" below.

![2023-09-11 193837](https://github.com/zxing-cpp/zxing-cpp/assets/136289338/65b5443b-3633-4ae1-a8c5-264edbf89448)

**Comment by axxel** [comment]
That is not entirely correct. Model 1 has no alignment patterns in any of the available sizes (or versions in QR speak). Model 2 Version 1 has no alignment patterns but higher versions have them. The most relevant difference is (quote) "symbol character placement follows different rules", i.e. the way the black/white squares are to be interpreted is different.

**Comment by sayzzy-nt** [comment]
thank you! I understood it well.

Model 1 and version 1 of model 2 are confusing.
Is there a way to tell them apart visually?
I did a quick search, but couldn't find any information on how to differentiate or how to decode Model 1...

**Comment by axxel** [comment]
> Is there a way to tell them apart visually?

If you have a Version 1 symbol (21 modules wide and high) then you are out of luck. For all symbols with higher Version numbers the Model 2 symbols have alignment patterns, Model 1 don't.

Your original sample is 29 modules wide, i.e. Version 3 and has no alignment patterns, therefore Model 1.

For information on how to decode them, you'd need the specification document.

**Comment by sayzzy-nt** [comment]
なるほど、それは難しいですね。 。 。
私のアプリはモデル 1 QR コードを読み取る必要があるため、この問題に対処する必要があります。
そこで、ご連絡させていただきたいと思います。

**Comment by sayzzy-nt** [comment]
I see, that's difficult.
My app needs to recognize model 1 QR code and I have to solve this problem.
So I would like to contact you.

**Comment by sayzzy-nt** [comment]
Dear axel

Thanks for contacting.
Yes, I am very interested in contributing my work.
That'd be my honor.

Best,

________________________________
差出人: axxel ***@***.***>
送信日時: 2023年10月17日 16:30
宛先: zxing-cpp/zxing-cpp ***@***.***>
CC: Nakatsubo Seiji ***@***.***>; Author ***@***.***>
件名: [EXTERNAL] Re: [zxing-cpp/zxing-cpp] QR Code Model 1 not supported (Issue #614)


I noticed that you published an implementation to support Model1 here<https://github.com/sayzzy-nt/zxing-cpp/commit/724a8e6c28d1d1b8e412ebef3b440005cf1efa76>. That is nice. Would you be interested in preparing a PR and contributing your work here?

**Comment by axxel** [comment]
> Yes, I am very interested in contributing my work.

That is very good to hear. I'll wait for your pull request then before looking closely at your changes and will provide feedback if I see something questionable.
