### ISSUE TITLE
One-dimensional code clarity problem?

### ISSUE THREAD

**Issue by PureHing** [zxing-cpp/zxing-cpp#642]
@axxel  Hi
For the recognition of these two pictures, can you give some suggestions for algorithm modification? ('1.bmp' cannot be recognized, '2.bmp' can be recognized)
can you give me some advice?
thanks
[test_bmp.zip](https://github.com/zxing-cpp/zxing-cpp/files/13072278/test_bmp.zip)

**Comment by axxel** [comment]
The problem is the combination of relatively low resolution and relatively low sharpness of the `1.bmp`. There is one thing you can do easily improve the situation in so far as then at least the EAN code in the `1.bmp` gets detected: replace the 1 with a 0 in this line: https://github.com/zxing-cpp/zxing-cpp/blob/b8c3d1a150d0290e29200a3ba839d7c076b77bf7/core/src/HybridBinarizer.cpp#L31

In general you may get better results by increasing the contrast or apply some sharpening before sending the image to zxing-cpp. That will especially be of help if your input is of similar type (used camera, lighting, resolution, etc.).

**Comment by PureHing** [comment]
@axxel Thank u for u reply.
Applying a sharpening filter can make ean recognized, but the one on the left in 1.bmp still doesn't work. Do you want to know if there is a way to improve the relevant preprocessing parameters in zxing-cpp so that this can be recognized?

**Comment by axxel** [comment]
> Do you want to know if there is a way to improve the relevant preprocessing parameters in zxing-cpp so that this can be recognized?

If I want to know? Sure, if you have some insight, I'd be interested to hear about it.

**Comment by PureHing** [comment]
@axxel 

Sorry, I made a mistake. It's "you know" instead of "you want to know". I sincerely want to ask you for advice.

**Comment by axxel** [comment]
I had another look at the code128 sample and can conclude that I don't think this decodable. The problem is that the lack of sharpness leads to a situation where some pixels that are supposed to be 'white' have the same value as others that are supposed to be 'black' so there is no threshold you can find that separates black from white in a way that it would work.
