### ISSUE TITLE
QRcode with  Chinese

### ISSUE THREAD

**Issue by sl00001** [zxing-cpp/zxing-cpp#663]
int main(int argc, char* argv[])
{
	std::wstring text = L"家国234567hgreh346346w+_=@#$%| a|";
	int width = 500, height = 500;
	int margin = 10;
	int eccLevel = 5;
	bool inputIsFile = false;
	std::string filePath = "D:/opencv/zxing-cpp-master/build/example/Release/QRCode.png";

	
	try {
		auto writer = MultiFormatWriter(BarcodeFormat::QRCode).setEncoding(CharacterSet::UTF8);

		auto bitmap = ToMatrix<uint8_t>(writer.encode(text, 500, 500));
		stbi_write_png(filePath.c_str(), bitmap.width(), bitmap.height(), 1, bitmap.data(), 0);
		std::cout << bitmap.width() << "\n";
	}
	catch (const std::exception& e) {
		std::cerr << e.what() << std::endl;
		return -1;
	}

	return 0;
}

Hello, the generated  QRcode with Chinese can be generated normally, but the following situations will occur when readQRcode.
I do not know why. thank you.

![截图20231115102301](https://github.com/zxing-cpp/zxing-cpp/assets/106507366/c80cda26-98f2-4814-91b4-606cee3170dd)

**Comment by sl00001** [comment]
![QRCode](https://github.com/zxing-cpp/zxing-cpp/assets/106507366/c7198da7-0e67-4db9-ae99-711ddf1210e9)

**Comment by axxel** [comment]
I see what you mean. I currently don't have time to look into this. This is yet another issue that is most certainly going to be fixed with #332. If that is an option for you, I would recommend looking into the libzint project (which is going to be used a writer backend for `zxing-cpp` at some point in time).

**Comment by cshaorui** [comment]
> 使用了不正确的编码?这句setEncoding(CharacterSet::UTF8); 我在默认utf8的系统里没发现乱码 ![IMG_20231204_194922](https://private-user-images.githubusercontent.com/82353054/287688168-a6e9abe5-75ad-4d1e-a7b7-d6e5cdde5195.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjE3MjAsIm5iZiI6MTcwMjcyMTQyMCwicGF0aCI6Ii84MjM1MzA1NC8yODc2ODgxNjgtYTZlOWFiZTUtNzVhZC00ZDFlLWE3YjctZDZlNWNkZGU1MTk1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDEwMTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYzJlZGU5ZWUyMGY4MmVhOGRhOGNlMGU3ZjJjZjlhNGQwNWQyZjUxZjZjNTJiOTNlOWIzM2YwMmQ5MDk2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZRTXgDR4S59kjvLx34f5VcGRRgD4kPNQUEdisgMoF7g)
有没有这方面的说明文档英文或中文,刚接触,在测试上面的代码时总出现错误:error LNK2019: 无法解析的外部符号 stbi_write_png，函数 main 中引用了该符号

**Comment by axxel** [comment]
@sl00001 it seems your issue is solved? I currently still don't see the problem in your example code but if I call
```sh
ZXingWriter -encoding utf8 qrcode "家国234567hgreh346346w+_=@#$%| a|" out.png
```
I get this result:
![weg](https://github.com/zxing-cpp/zxing-cpp/assets/1038346/aedeed1e-052b-48c2-901f-dcdf15aef5eb)

@cshaorui please have a look at [this and the following line](https://github.com/zxing-cpp/zxing-cpp/blob/d333f8685bb65dd80b106f24d608c1ce9aaa891c/example/ZXingWriter.cpp#L20). `stbi_write_png` is from an external image library.

**Comment by axxel** [comment]
Closing for lack of feedback.
