### ISSUE TITLE
Regression on read success with bad quality QRcodes

### ISSUE THREAD

**Issue by urishab** [zxing-cpp/zxing-cpp#667]
I'm seeing a regression in the ability to read bad quality QR codes with the recent versions

I have a low quality QR code where I do the thresholdig myself because the default Binarizer fail.
An example after threshold is attached.
Reading this with the old 1.4.0 release works fine but trying to read it with the current master (which is probably similar to 2.1.0) fails.

Am I missing some flag to improve reading QRCodes?
Unfortunately this is not a one time thing

![hard_small_white](https://github.com/zxing-cpp/zxing-cpp/assets/1208625/13183f23-0fe0-418f-b478-2741060fe32d)

**Comment by urishab** [comment]
I tried a few more versions and the regression happens between version 2.0.0 and 2.1.0

**Comment by axxel** [comment]
The sample you provided fails with a checksum error. If you look at the grid placement below, you can see that there is nothing to complain about with respect to where the grid was sampled. There have been changes to the QRDetector that substantially improved the situation with high resolution symbols. It might very well be that some older code placed that grid slightly differently which might have resulted in a few or maybe just one different sampling point which could be enough to make it just work. But I don't see a point in trying to hunt down which exact change made this fail and try to revert it. I you have more samples, feel free to add them here. Maybe that will reveal a systematic pattern.

**Comment by urishab** [comment]
After some testing with more samples, it looks like the problem is actually with the binarizer
Trying simple thresholding with every possible value solves each of the hard cases I encountered
Both LocalAverage and GlobalHistogram fail again and again on hard cases.

So has there been a change to the LocalAverage binarizer that could explain this regression?

here's another example
![hard_t3_small](https://github.com/zxing-cpp/zxing-cpp/assets/1208625/9823065d-8692-45f0-a44d-ff26a1c12c55)

Here's the example I put in the original issue before the manual thresholding:
![hard_t15_small](https://github.com/zxing-cpp/zxing-cpp/assets/1208625/14f1a285-b244-43bf-aaf4-6eb1f9ea7eda)

**Comment by axxel** [comment]
I don't recall a change there but I have not checked. One thing I noticed while looking at your original input is that the resolution is actually the main problem here. I did a quick experiment and noticed that if I simply upscale the images by a factor of 2 with simple linear interpolation then both of them work out of the box. Maybe that could be a workaround for your use case instead of "manual" thresholding?

**Comment by urishab** [comment]
I tested the 2X method and it definitely works and very well
I'm surprised that it does but will incorporate this into the workflow
Maybe it's worthwhile adding it to the package, maybe with the try_harder flag?

**Comment by axxel** [comment]
Thanks for the feedback. If we add it, I would rather add something like `tryUpscale` as a complement to the existing `tryDownscale`. But I'm not convinced at this point in time that this would be worth it as it seems to me to be a very niche problem. 

Note that I would assume the resolution you have would actually work if you scanned QRCodes with Version 2 and up, because they have an additional alignment pattern in the lower right which helps with fine-tuning the grid placement. If you have such a symbol that still only works with the 2x method, I'd be curious to see it.

**Comment by urishab** [comment]
ok thanks, closing the issue
