### ISSUE TITLE
`isValid` regression after 643520c

### ISSUE THREAD

**Issue by Sec-ant** [zxing-cpp/zxing-cpp#691]
I noticed a regression of the `isValid` value after 643520c when detecting the following image:

![](https://github.com/zxing-cpp/zxing-cpp/assets/10386119/a07cc3bc-904b-4164-bdd1-60d123b7e772)

**Before 643520c:**

If `returnErrors` option is turned on, 3 QR Code symbols and 2 PDF417 symbols are detected, and the `isValid` values of the 2 PDF417 symbols are `false`.

**After 643520c:**

If `returnErrors` option is turned on, 3 QR Code symbols and 2 PDF417 symbols are detected, and the `isValid` values of the 2 PDF417 symbols are `true`.

**Expected behavior:**

The PDF417 symbols are false positives therefore the `isValid` values should be `false`.

I first noticed this problem on my site: https://zxing-wasm-demo.netlify.app/. And I confirmed it with the wasm wrapper in this repo as well (I manually added `isValid` and `returnErrors` to the binding code)

The detected result 👇 
![](https://github.com/zxing-cpp/zxing-cpp/assets/10386119/08ddb66d-1616-4736-88d0-a2662610141e)

**Comment by axxel** [comment]
Thanks for this very complete and informative bug reporting. This is so much better than the average report I get here...

The reason is, I changed the implementation of `isValid` to allow for symbologies without a standard symbology identifier. The point is, I need to detect a default constructed / empty result. The most natural way should actually be to check for an empty content but I was not sure whether that would exclude valid barcodes, e.g. once with no content but only a `readerInit` flag.

@gitlost trying to use zint-qt to generate an empty datamatrix symbol with only the `Reader Init` flag set results in an Error 778. Do you know if an empty content necessarily results in an invalid symbol according to the spec?

**Comment by gitlost** [comment]
Zint insists on non-empty data always for all barcodes, but no, I don't see anything in the spec that prohibits a symbol just being filled with pad characters...

**Comment by axxel** [comment]
Thanks @gitlost. That is enough information for me be pragmatic and define empty codes as invalid until someone makes a case to support them.
