### ISSUE TITLE
Inverted QRCode not recognized

### ISSUE THREAD

**Issue by hangj** [zxing-cpp/zxing-cpp#709]
The following qrcode can not be recognized:  

<img src="https://github.com/zxing-cpp/zxing-cpp/assets/3966159/59cdf6d9-92c0-4846-8cd1-4d9b5d9c229b" width=200 />

**Comment by axxel** [comment]
For the most part I'll quote myself from [here](https://github.com/zxing-cpp/zxing-cpp/issues/575#issuecomment-1589715589): The image fails because the inversion (see `tryInvert()`) happens after the binarization (for performance reasons) and the LocalAverage binarizer has a bias for light backgrounds. If you invert the image outside of zxing-cpp, then it works in your case. If you generally have to deal with inverted input like this, I would recommend to invert the images and set `ReaderOptions::tryInverted(false)`.

There are two other possibilities to make this particular image work:
1. crop the barcode
2. get rid of the dark square at the top-left and then use the `GlobalHistogram` binarizer.

**Comment by hangj** [comment]
@axxel Thank you for the reply, it is very helpful.

**Comment by axxel** [comment]
This is fixed in HEAD now.
