### ISSUE TITLE
iOS & Android Qt

### ISSUE THREAD

**Issue by niqt** [zxing-cpp/zxing-cpp#713]
Hi,
is the Qt version running on Android and iOS?

**Comment by axxel** [comment]
There is no "Qt version". There is only some example code that provides a Qt interface to the reader functionality. I would assume that code can be made to run on iOS and Android but there has not changed anything in this regard since you asked the same question the last time: #603. If have an issue, you need to provide specific details about what is not working.

**Comment by niqt** [comment]
Ok, I have still the same problem, on android the app starts with a frozen camera and crashes. I'll try to understand what's happening.

**Comment by axxel** [comment]
Have you made any progress with your understanding? Without further feedback from you, I will close this issue as I did with the last one.

**Comment by niqt** [comment]
No progress. Close for now, when i'll have progress, i'll tell you
