### ISSUE TITLE
EAN causing Assertion `lineCount() == 1' fail

### ISSUE THREAD

**Issue by BenoitAnastay** [zxing-cpp/zxing-cpp#740]
From Paperless-NGX when I try to pass this file [European.Article.Number.Wikipedia.pdf](https://github.com/zxing-cpp/zxing-cpp/files/14438081/European.Article.Number.Wikipedia.pdf) through barcode recognition I get ```./core/src/Result.cpp:140: bool ZXing::Result::operator==(const ZXing::Result&) const: Assertion `lineCount() == 1' failed.```

ZXing version : python3-zxing-cpp=1.4.0-3+b1 https://packages.debian.org/bookworm/mipsel/python/python3-zxing-cpp

https://github.com/paperless-ngx/paperless-ngx/issues/5936
https://github.com/BenoitAnastay/paperless-home-assistant-addon/issues/108

**Comment by axxel** [comment]
I need additional information to be able to investigate this. First and foremost a means to replicate the problem. The Paperless-NGX software uses our python module, right? Which version is used? And since we don't directly support scanning PDF files, there must be some internal PDF -> bitmap rendering happening. I'd need the exact bitmap data that is passed to `zxingcpp.read_barcodes()` to be able to debug this.

**Comment by BenoitAnastay** [comment]
> Did you build the module yourself?

I'm using debian package, It seems outdated.

This issue is already fixed in last release

**Comment by axxel** [comment]
Never mind my last comment. Yes, 1.4.0 is completely outdated. Current testing version is 2.2.1-3 and is pretty up-to-date.
