### ISSUE TITLE
Inverted, mirrored, dotted DataMatrix failed to decode

### ISSUE THREAD

**Issue by gloomyfish1998** [zxing-cpp/zxing-cpp#774]
![9010](https://github.com/zxing-cpp/zxing-cpp/assets/30948147/fdea7d14-2916-4f6f-a3fa-f16812fd74ff)
c
![9010](https://github.com/zxing-cpp/zxing-cpp/assets/30948147/d62ed1ed-9d98-4db9-91f4-edb14c971f67)
zxing2.2 can not prase this data matrix code while other DM decode library can decode it 
and zxing did not give any error msg when decode failure~~~~
can you tell me the reason info why zxing blocked this dm code prase, please help me on this 

i want to know the reason, thanks a lot~~~

**Comment by gloomyfish1998** [comment]
i already try the pre-process and binary/dilate/erode , did not work at all

**Comment by axxel** [comment]
Interesting sample you have there: the first image is inverted, mirrored, rotated and uses dots. If I normalize this, I get the following:
![#774-1-clean](https://github.com/zxing-cpp/zxing-cpp/assets/1038346/c1aa31b2-95b7-4097-837d-a978d1994816)

This still does not work because there is an [invalid](https://github.com/zxing-cpp/zxing-cpp/blob/c4668ab9bca779a2e88ec5355f65947472c39875/core/src/datamatrix/DMDecoder.cpp#L293) `0` in the bit stream at position 6: 206, 60, 123, 182, 203, **0**, 182, 178.

The decoded text until that point reads `76;z5273`.

@gitlost, @oehhar: can you confirm from the top of your head that this is indeed an invalid bit stream and failing to decode this is the only proper way?

**Comment by gloomyfish1998** [comment]
thanks your reply, i wan to know how to binary image like you get ~~~~
thanks a lot~~~~

**Comment by axxel** [comment]
I used GIMP: invert -> erode -> erode -> erode -> dilate -> dilate -> dilate -> flip -> rotate -> crop -> threshold(150)

**Comment by axxel** [comment]
I took the idea of your fix and applied a "version" of it: decode the full message, even if an error occurs. Now the returned info if the `ReaderOptions::returnErrors()` flag is set looks like this:
```
Text:       "76;z52735248"
Bytes:      37 36 3B 7A 35 32 37 33 35 32 34 38
Format:     DataMatrix
Identifier: ]d1
Content:    Text
HasECI:     false
Position:   42x23 186x21 187x167 43x169
Rotation:   -1 deg
IsMirrored: true
IsInverted: false
Version:    3
Error:      FormatError (invalid 0 code word) @ DMDecoder.cpp:299
```

If you don't have anything else to add to the discussion, please close the issue.
