### ISSUE TITLE
AndroidManifest.xml:2 Android Build Error

### ISSUE THREAD

**Issue by ffreality** [zxing-cpp/zxing-cpp#783]
Master branch gives this error when I try to build for Android from both Windows 11 and WSL2 Ubuntu 22.04

**Installed Environment**
Android Studio 2023.3.1
openjdk 21.0.2 2024-01-16
Gradle 8.7
NDK 25.1
Android Studio SDK from Android 8.1 to Android 14

All paths set.

`zxing-cpp/wrappers/android/zxingcpp/build/intermediates/aapt_friendly_merged_manifests/release/aapt/AndroidManifest.xml:2: AAPT: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'zxingcpp'.`

**Comment by ffreality** [comment]
Any suggestion ?

**Comment by axxel** [comment]
I had a look at this and to my surprise, I could indeed reproduce the issue when building a release build via `./gradlew :zxingcpp:assembleRelease` as supposed to a debug build (which is what the CI system does). After some random experiments to determine where exactly the string `zxingcpp` in the autogenerated AndroidManifest.xml comes from, it turns out that is from here:
https://github.com/zxing-cpp/zxing-cpp/blob/d0c1f343e2b17847ec7d26642ed09af643492eaa/wrappers/android/zxingcpp/build.gradle.kts#L9
If you change that string to e.g. `zxingcpp.lib` it builds again. This used to work in the past and I believe some tool chain update broke this. I currently don't have a clear understanding of the implications of changing this `namespace` property with respect to the published android package and any client side code. There is some documentation to be found [here](https://developer.android.com/build/configure-app-module)

@markusfisch do you have an insights in this regard?

**Comment by markusfisch** [comment]
I wouldn't have known this before I checked the docs, but I'm surprised it ever worked without a dot, because according to the documention you mentioned, the `applicationId` "must have at least two segments (one or more dots)". And since `namespace` and `applicationId` [should be the same](https://developer.android.com/build/configure-app-module#change_the_package_name), this also applies to `namespace`. Maybe past build tools didn't check the application ID, but I don't know.

Now, since the `namespace` is only used as package name for the generated `R` and `BuildConfig` classes of a module, and because the wrapper doesn't have any resources, changing it _should_ have no effect for the published packages. And indeed, I can confirm that the `aar` does still have the same package name ("zxingcpp") for its classes even with a different `namespace` ("zxingcpp.lib").

On the other hand, I would still suggest switching to a multi-part package name for the whole module.

**Comment by ffreality** [comment]
> I had a look at this and to my surprise, I could indeed reproduce the issue when building a release build via `./gradlew :zxingcpp:assembleRelease` as supposed to a debug build (which is what the CI system does). After some random experiments to determine where exactly the string `zxingcpp` in the autogenerated AndroidManifest.xml comes from, it turns out that is from here:
> 
> https://github.com/zxing-cpp/zxing-cpp/blob/d0c1f343e2b17847ec7d26642ed09af643492eaa/wrappers/android/zxingcpp/build.gradle.kts#L9
> 
> 
> If you change that string to e.g. `zxingcpp.lib` it builds again. This used to work in the past and I believe some tool chain update broke this. I currently don't have a clear understanding of the implications of changing this `namespace` property with respect to the published android package and any client side code. There is some documentation to be found [here](https://developer.android.com/build/configure-app-module)
> @markusfisch do you have an insights in this regard?

I changed it to `zxingcpp.lib` it builds with `gradlew ::zxingcppAssembleRelease` on Windows 11.
But UE5 gives this error.

```
UATHelper: Packaging (Android (ASTC)): ld.lld: error: undefined symbol: ZXing::MultiFormatWriter::encode(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, int, int) const
UATHelper: Packaging (Android (ASTC)): >>> referenced by FF_QR_ProcessorBPLibrary.cpp:217 (D:/Projects/FROZEN/SDKs/UE/FF_Plugins_Mobile/Plugins/FF_QR_Processor/Source/FF_QR_Processor/Private/FF_QR_ProcessorBPLibrary.cpp:217)
UATHelper: Packaging (Android (ASTC)): >>>               D:/Projects/FROZEN/SDKs/UE/FF_Plugins_Mobile/Plugins/FF_QR_Processor/Intermediate/Build/Android/a/UnrealGame/Development/FF_QR_Processor/FF_QR_ProcessorBPLibrary.cpp.o:(UE::Core::Private::Function::TFunctionRefCaller<UFF_QR_ProcessorBPLibrary::ZXing_Encode(FDelegateQrEncode, FString, EZXingFormat, UE::Math::TVector2<double>, int, FColor, FColor)::$_3, void ()>::Call(void*))
UATHelper: Packaging (Android (ASTC)): clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Packaging (Android (ASTC)): Total time in Parallel executor: 11.00 seconds
PackagingResults: Error: undefined symbol: ZXing::MultiFormatWriter::encode(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, int, int) const
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried these .so files
- intermediates/merged_native_libs/
- extracted from .aar file

This is the line 220 of my encoder.
https://github.com/FF-Plugins-Active/FF_QR_Processor/blob/main/Source/FF_QR_Processor/Private/FF_QR_ProcessorBPLibrary.cpp#L220

**Comment by axxel** [comment]
Looking at your code, it seems to me you are not using the android wrapper (JVM code) at all, but rather only the native library directly? The encoder/writer part is simply no build for the android wrapper at the moment. You can try to simply change [this line](https://github.com/zxing-cpp/zxing-cpp/blob/d0c1f343e2b17847ec7d26642ed09af643492eaa/wrappers/android/zxingcpp/build.gradle.kts#L23) by setting the `-DBUILD_WRITERS=ON` and see how far that brings you.

As for a static library: that can't possibly work for the JNI bridge but in your use-case that should be possible somehow. But I have not sufficient expertise in the android/gradle build environment to help you there.

**Comment by ffreality** [comment]
> Looking at your code, it seems to me you are not using the android wrapper (JVM code) at all, but rather only the native library directly? The encoder/writer part is simply no build for the android wrapper at the moment. You can try to simply change [this line](https://github.com/zxing-cpp/zxing-cpp/blob/d0c1f343e2b17847ec7d26642ed09af643492eaa/wrappers/android/zxingcpp/build.gradle.kts#L23) by setting the `-DBUILD_WRITERS=ON` and see how far that brings you.
> 
> As for a static library: that can't possibly work for the JNI bridge but in your use-case that should be possible somehow. But I have not sufficient expertise in the android/gradle build environment to help you there.

I don't know which version but there is a zxing based plugin in Unreal Marketplace. If I use her includes and .a static library, it packages and works perfectly with same code.

I don't use her plugin because it wasn't asynchronous and I needed to modify it to work with RealSense without using unnecessary memcpy.

I don't want to use her library because it is not up to date.

**Comment by ffreality** [comment]
> Looking at your code, it seems to me you are not using the android wrapper (JVM code) at all, but rather only the native library directly? The encoder/writer part is simply no build for the android wrapper at the moment. You can try to simply change [this line](https://github.com/zxing-cpp/zxing-cpp/blob/d0c1f343e2b17847ec7d26642ed09af643492eaa/wrappers/android/zxingcpp/build.gradle.kts#L23) by setting the `-DBUILD_WRITERS=ON` and see how far that brings you.
> 
> As for a static library: that can't possibly work for the JNI bridge but in your use-case that should be possible somehow. But I have not sufficient expertise in the android/gradle build environment to help you there.

tried and problem continues.

**Comment by ffreality** [comment]
Partially solved the problem.
Unreal Marketplace developer builds ZXing with their own custom Android.mk file and she shared it with source code.

When I looked at StackOverflow about this problem, they said that both library and application had to built as APP_STL := c++_static.

https://stackoverflow.com/a/71331912
