### ISSUE TITLE
Any plan to add hybrid binarizer as an option for python wrapper?

### ISSUE THREAD

**Issue by drsagat** [zxing-cpp/zxing-cpp#799]
The binarizer options in python wrapper currently only have BoolCast, FixedThreshold, GlobalHistogram, LocalAverage, which makes it hard to 100% mimic the behavior of the website(zxing.org).

**Comment by axxel** [comment]
The `LocalAverage` in the `zxing-cpp` project is basically the `HybridBinarizer` in the `zxing(.org)` project. That said, there are details that make them behave slightly differently. But more importantly, most of the detection code for the individual symbologies changed significantly since this c++ port has been started from the Java code base many years ago. So there is no way to mimic zxing.org's behavior with the `zxing-cpp` python wrapper.
