### ISSUE TITLE
Finding only a few of many QRCode symbols in one image

### ISSUE THREAD

**Issue by lykius** [zxing-cpp/zxing-cpp#831]
Hi, I'm trying to use `zxing` in a project where I need to split some information over multiple qr codes.
I cannot decode the following image (27 qr codes containing meaningless strings like "AAAAAAAA"):
![failed_1](https://github.com/user-attachments/assets/dfc234fa-4431-4ae0-8ca3-e9f23cab33b2)
I would expect the detection to work seamlessly, since the image is "perfect" (it's a not a picture taken from some camera, it's generated by the computer).  
With the python wrapper version 0.2.2 only 4 qr codes out of 27 are decoded, while things are better with the online decoder, which finds 17 qr codes out of 27.

Any idea on what's going on and how to improve the result?
Thanks in advance!

**Comment by axxel** [comment]
The reason for your issue is the number 256 in [this line](https://github.com/zxing-cpp/zxing-cpp/blob/39ebe724389913441689dc3cc56247eeeda866cb/core/src/qrcode/QRDetector.cpp#L185). It limits the number of combinations of similar sized finder patterns to combine into a potential qrcode symbol. With 81 of those patterns, the theoretical number of combinations is  81! / (78! * 3!) = 85319.

A quick fix for this case is to simply change that 256 to say 256000. This increases the runtime from 4ms to 14ms, which is a lot better than I feared when I set the value to 256.

The situation would become substantially better if you had a photograph of those 27 symbols instead of a perfect rendering because then they would differ slightly in size and the size is used to sort them prior to trying the combinations. Is this rendering indeed what you want to process in the end or was it your attempt to make the input "easier" to process and debug the issue?

**Comment by lykius** [comment]
This worked perfectly, thank you so much!

About your question: this was a test during the development of the rendering part, to see if `zxing` was able to detect/decode what I was generating. I'm not sure about the real-life use case, it could be that the user will process only photographs, but it could also be that the user has the original rendered image and wants to decode the info from the qr codes. Since inference time is not a strict constraint, I will probably increase the limit as you suggested.  

Thanks again!

**Comment by lykius** [comment]
Thanks for the hints, I'll keep you posted.
Closing for now!

**Comment by axxel** [comment]
I reopened it, since the library as is still has this (serious) limitation and I see the need to do something about it, sooner or later...

**Comment by adamponi** [comment]
Very good idea. Temporarily, at least a little bit, we will increase this value a little in the main line.

Thank you

**Comment by axxel** [comment]
Fixed in ab4b74554eb8a02fae361d1a1f2a6138d1484577.
