### ISSUE TITLE
Multithreading / Thread Safety / Usage scenarios

### ISSUE THREAD

**Issue by axxel** [zxing-cpp/zxing-cpp#92]
My recent thread-safety regression (see #91) raised a question: what is the use case for supporting multi-threading / thread-safety?

The current state of the code promises thread-safety on a 'decoder object level' (if I'm not mistaken, that is). I.e. you can instantiate e.g. a `MultiFormatReader` and then share that with several threads who work on different images concurrently. What they then share is basically the `DecoderHints` that are stored inside the decoder objects.

My recent regression fix would not be required if the different threads would simply be required to instantiate their own `MultiFormatReader`. Is there an advantage of sharing that reader object across threads?

What is the use-case for having multiple threads work on separate images in the first place? I see how that could speed up the blackbox-testrunner but in a typical (mobile) app: where do those multiple images come from? Would it not be significantly better if the `MultiFormatReader` used multi-threading internally to decode one image at a time faster?

There are several parallelism opportunities:
 1. run multiple decoders in parallel on the same image data
 1. run the 1D decoders in parallel on different scan-lines

**Comment by huycn** [comment]
@axxel In our real usecase, we create `MultiFormatReader` upfront, and then in a loop, we grab one frame on the camera and start the scan in a new async task (which will be distributed among a limited set of threads). Therefore, if the camera is fast enough, we may have multiple frames decoded in parallel. If `MultiFormatReader` was not thread-safe, we need to recreate it for every picture frame. Since creation of `MultiFormatReader` involes many `new`, the cost is non-negligible (compared with the duration of the scan of course).

If `MultiFormatReader` was not thread-safe, to avoid recreate it every time, we could also create some kind of static thread local variable. But static variables comes with their own issues.

For two parallelism opportunities you mentioned, this implies that ZXing must support it and clients don't have much control on it. We could abstract it (e.g. with a kind TaskScheduler), however beside an API more complex, I doubt the overload will outweigh the performance gain, especially for the second case.

**Comment by axxel** [comment]
Thanks for the background info. What you'd need to make it work even without `MultiFormatReader` being inherently thread-safe would be an instance per thread, not per image frame. But, it would indeed be conceptually easier to handle if it stayed as thread-safe as it was.

I thought you might do this kind of multi-threading (decode frames in parallel) but if you could choose, would it not be better to have each frame decode twice as fast instead of being able to decode two frames in parallel. I assume your application (any mobile app actually) is basically to look for codes until one is found. Then stop and report back. So it only introduces latency if you were looking at 5 frames in parallel instead of just one and be done with it before the next one comes?

How many threads do you have in your pool working on individual frames?

What I thought of conceptually was some kind of internal thread-pool-whatever that you basically opt in by giving the `MultiFormatReader` an `int thread_count` kind of parameter and that's it.

**Comment by huycn** [comment]
Yes, it's not always obvious to have one reader per thread since at the level where we create the reader, we don't manage threads. So the remaining option is what I mentioned, with thread-local variable. However, thread-local variables don't go well with task-based parallelism. It's not a big issue in this case as the worse case is we recreate reader, however it's still better to avoid it. There is another bigger issue with thread-local is that we will need to care how to clean them up, make sure that they don't stay longer than necessary.

I'm not sure what is better if we take into account implementation's complexity. The problem with a slow frame rate is not that we get the result 0.5 second slower, but it will make detection much harder. In one of our usecases, barcode detection is one among other "filters", thus if we take too much time to process the frame, it will affect also the focusing process, thus it becomes really hard to get a clear picture. We have seen that on first generation of Surface tablets, I guess because they implemented the focus in software instead of hardware, but I'm not sure.

For the number of threads in the pool, we don't have control and it's very likely implementation and device dependent (the number of virtual CPU cores).

Yes, we surely can do it, but is it still simpler to leave the control of parallelism to our client instead of handling our-self? Also, on mobile platform, threads are expensive, as a client, I prefer to pass a threadpool to a library to use than it spawn threads by itself. Moreover, these days, threadpools are inferior to task-based implementation in many aspects. With current implementation of this library, one task per frame is already good, I believe by introducing parallelism at smaller scale, it would add more overhead without visible benefits. Note that if we clients want multiple decoders in parallel on the same image data, they can already do that.

**Comment by axxel** [comment]
I consider this discussion to be outdated.
